# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50890ff887a2f9bd2a1bf13a8a065a87caa0a0b765ccad45a4f69e1768d76f2094625afde4cf879775706a64c666b679f72ec7869cbe8fb58b02bf91a88121d9

test:
  secret_key_base: 35132899bbab774cefd0bb38721ba025ca69e115ef37e3f29d28ec2bd19a14b8a46c45038972ea4654cb5100079094122b4175e88dc3f6fa47e1f6a9b7888f02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
